name: DEPLOY

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-to-dev:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          aws eks update-kubeconfig --name main-dev-eks
          DATE=$(date)
          echo $DATE
          exit 1

  deploy-to-qa:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    environment: qa
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  functional-tests:
    runs-on: self-hosted
    needs: [deploy-to-qa]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  e2e-tests:
    runs-on: self-hosted
    needs: [deploy-to-qa]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  deploy-to-stage:
    runs-on: self-hosted
    needs: [e2e-tests, functional-tests]
    environment: stage
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  deploy-to-prod:
    runs-on: self-hosted
    needs: [deploy-to-stage]
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
